name: cicd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-testing:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Build
      run: |
        python3 -m venv .env
        source .env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip list

    - name: Use pylint
      run: |
        pip list
        find . -maxdepth 1 -name "*.py"
        find . -maxdepth 1 -name "*.py" | xargs pylint --exit-zero


    - name: Testing
      run: |
        source .env/bin/activate
        pytest tests.py 