name: cicd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        which pip
        python3 -m venv .env
        source .env/bin/activate
        which pip
        pip install --upgrade pip
        pip install -r requirements.txt
        ls -la
        pip list